apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: es-config-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/JulienDanh/argo-resharding.git"
    targetRevision: HEAD
    path: es-config-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: config-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
