---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: first-cluster
spec:
  version: 8.13.4
  nodeSets:
    - name: default
      count: 2
      config:
        node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart-kibana
spec:
  version: 8.13.4
  count: 1
  elasticsearchRef:
    name: quickstart
