apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: es-config-resharding-operator
rules:
  - apiGroups: ["elasticsearch.example.com"]
    resources: ["reshardings"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: es-config-resharding-operator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: es-config
roleRef:
  kind: ClusterRole
  name: es-config-resharding-operator
  apiGroup: rbac.authorization.k8s.io 