# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/elasticsearch.k8s.elastic.co/elasticsearch_v1.json
{{- range .Values.clusters }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ . }}
spec:
  version: 8.13.4
  nodeSets:
    - name: default
      count: 2
      config:
        node.store.allow_mmap: false
---
{{- end }}
